name: PBRP Build (Nubia Cerro/支持双树)

on:
  workflow_dispatch:
    inputs:
      MANIFEST_URL:
        description: 'PBRP Manifest 源码'
        required: true
        default: 'https://github.com/PitchBlackRecoveryProject/manifest_pb'
      MANIFEST_BRANCH:
        description: 'PBRP 源码分支'
        required: true
        default: 'android-12.1'
      DEVICE_TREE_URL:
        description: '目标设备树仓库 (Device Tree)'
        required: true
        default: 'https://github.com/delvoryx/android_device_nubia_cerro-recovery'
      DEVICE_TREE_BRANCH:
        description: '目标设备树分支'
        required: true
        default: 'fox_14.1'
      DEVICE_PATH:
        description: '目标设备树存放路径'
        required: true
        default: 'device/nubia/cerro'
      COMMON_TREE_URL:
        description: '公共树仓库 (Common Tree) - 若无则留空'
        required: false
        default: ''  # <--- 如果你有 cerro 的公共树，将链接填在这里
      COMMON_PATH:
        description: '公共树存放路径 - 若无则留空'
        required: false
        default: ''  # <--- 例如: device/nubia/sm8650-common
      DEVICE_NAME:
        description: '设备代号'
        required: true
        default: 'cerro'
      MAKEFILE_NAME:
        description: 'Makefile 名称 (用于 lunch 命令)'
        required: true
        default: 'twrp_cerro-ap2a'
      BUILD_TARGET:
        description: '编译目标'
        required: true
        default: 'recovery'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-24.04
    env:
      TIMESTAMP: 20260707
    permissions:
      contents: write
    steps:
    - name: Display Run Parameters
      run: |
        echo "::group::User Environment Variables"
        echo "Manifest URL: ${{ github.event.inputs.MANIFEST_URL }}"
        echo "Manifest Branch: ${{ github.event.inputs.MANIFEST_BRANCH }}"
        echo "Device Tree URL: ${{ github.event.inputs.DEVICE_TREE_URL }}"
        echo "Device Tree Branch: ${{ github.event.inputs.DEVICE_TREE_BRANCH }}"
        echo "Device Path: ${{ github.event.inputs.DEVICE_PATH }}"
        echo "Common Tree URL: ${{ github.event.inputs.COMMON_TREE_URL }}"
        echo "Common Path: ${{ github.event.inputs.COMMON_PATH }}"
        echo "Device Name: ${{ github.event.inputs.DEVICE_NAME }}"
        echo "Makefile Name: ${{ github.event.inputs.MAKEFILE_NAME }}"
        echo "Build Target: ${{ github.event.inputs.BUILD_TARGET }}.img"
        echo "::endgroup::"

    - name: Check Out
      uses: actions/checkout@v4


    - name: Prepare the environment
      run: |
        sudo apt update && sudo apt upgrade -y
        DEBIAN_FRONTEND=noninteractive sudo apt install -yq \
            linux-modules-extra-$(uname -r) \
            gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib \
            libc6-dev lib32ncurses-dev x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils \
            xsltproc bc ccache lib32readline-dev lib32z1-dev liblz4-tool libncurses-dev libsdl1.2-dev \
            build-essential libgtk-3-dev libglu1-mesa-dev freeglut3-dev git libxml2 lzop pngcrush schedtool squashfs-tools \
            imagemagick libbz2-dev lzma ncftp qemu-user-static libstdc++-10-dev libncurses6 python3 tar

    - name: Install OpenJDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Install repo
      run: |
        mkdir ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo

    - name: Initialize repo
      run: |
        mkdir workspace
        cd workspace
        echo "workspace-folder=$(pwd)" >> $GITHUB_OUTPUT
        git config --global user.name "Nico170420"
        git config --global user.email "b170420nc@gmail.com"
        repo init --depth=1 -u ${{ github.event.inputs.MANIFEST_URL }} -b ${{ github.event.inputs.MANIFEST_BRANCH }}
      id: pwd

    - name: Repo Sync
      run: |
        repo sync -j$(nproc --all) --force-sync
      working-directory: workspace

    - name: Clone device tree (目标设备树)
      run: |
        git clone ${{ github.event.inputs.DEVICE_TREE_URL }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} ./${{ github.event.inputs.DEVICE_PATH }}
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}

    - name: Clone common tree (公共设备树)
      if: |
        github.event.inputs.COMMON_TREE_URL != ''
        && github.event.inputs.COMMON_PATH != ''
      run: |
        # 智能判断：只有当你填了 COMMON_TREE_URL 时，才会执行克隆公共树的动作
        git clone ${{ github.event.inputs.COMMON_TREE_URL }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} ./${{ github.event.inputs.COMMON_PATH }}
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}

    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 12

    - name: Building PBRP Recovery
      run: | 
        # ================== 自动注入修复补丁 ==================
        echo "TARGET_RECOVERY_DEVICE_MODULES += zstd" >> ${{ github.event.inputs.DEVICE_PATH }}/${{ github.event.inputs.MAKEFILE_NAME }}.mk
        echo "TW_RECOVERY_ADDITIONAL_RELINK_FILES += \$(TARGET_OUT_EXECUTABLES)/zstd" >> ${{ github.event.inputs.DEVICE_PATH }}/${{ github.event.inputs.MAKEFILE_NAME }}.mk
        echo "TW_INTERNAL_STORAGE_PATH := /sdcard" >> ${{ github.event.inputs.DEVICE_PATH }}/${{ github.event.inputs.MAKEFILE_NAME }}.mk
        echo "TW_DEFAULT_STORAGE_PATH := /sdcard" >> ${{ github.event.inputs.DEVICE_PATH }}/${{ github.event.inputs.MAKEFILE_NAME }}.mk
        echo "TW_RECOVERY_SETTINGS_PATH := /data/media/0/PBRP/.pbrps" >> ${{ github.event.inputs.DEVICE_PATH }}/${{ github.event.inputs.MAKEFILE_NAME }}.mk
        # ======================================================
        
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        
        # 使用你指定的 lunch 名称，并加入了 mka adbd recoveryimage 的编译逻辑
        lunch ${{ github.event.inputs.MAKEFILE_NAME }}-eng && make clean && mka adbd ${{ github.event.inputs.BUILD_TARGET }}image -j$(nproc --all)
        
        TIMESTAMP=$(date +"%Y%m%d%H%M")
        echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV
        cp out/target/product/${{ github.event.inputs.DEVICE_NAME }}/${{ github.event.inputs.BUILD_TARGET }}.img ../PBRP-${{ github.event.inputs.DEVICE_NAME }}-$TIMESTAMP.img
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}

    - name: Upload to Release
      uses: softprops/action-gh-release@v2
      with:
        files: | 
          *.img
        name: PBRP-${{ github.event.inputs.DEVICE_NAME }}-${{ env.TIMESTAMP }}
        tag_name: PBRP-${{ env.TIMESTAMP }}
        body: |
          ### PBRP 编译成功 
          - 设备: ${{ github.event.inputs.DEVICE_NAME }}
          - 目标树: ${{ github.event.inputs.DEVICE_TREE_URL }}
          - 公共树: ${{ github.event.inputs.COMMON_TREE_URL || '无' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
